[program:oxxogas_contactos_worker]
command=python3 /app/cron_sync_oxxogas_contactos.py
directory=/app
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/oxxogas_contactos_worker_err.log
stdout_logfile=/var/log/supervisor/oxxogas_contactos_worker.log
environment=CRON_OXXOGAS_CONTACTOS_INTERVAL="21600"